# Generated by Django 4.0.5 on 2022-08-09 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='camioneros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Completo', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoentidad', models.PositiveSmallIntegerField(choices=[(1, 'Camioneros'), (2, 'Cliente')], verbose_name='Tipo_Entidad')),
                ('Documento', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Provincia', models.PositiveSmallIntegerField(choices=[(1, 'Buenos Aires'), (2, 'Cordoba'), (3, 'Corrientes'), (4, 'Entre Ríos'), (5, 'Santa Fe'), (6, 'Santiago del Estero')], verbose_name='Provincia')),
                ('Codigopost', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehiculo', models.PositiveSmallIntegerField(choices=[(1, 'Camion'), (2, 'Acoplado')], verbose_name='Tipo_Veh')),
                ('Patente', models.CharField(max_length=7)),
                ('DescripVeh', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fechacarga', models.DateTimeField(auto_now=True)),
                ('Fecha', models.DateField()),
                ('Tipodoc', models.PositiveSmallIntegerField(choices=[(1, 'C.T.G'), (2, 'Remito')], verbose_name='Tipo Documento')),
                ('Documento', models.CharField(max_length=10)),
                ('Kilometros', models.PositiveSmallIntegerField(choices=[(1, '50'), (2, '100'), (3, '150'), (4, '200'), (5, '250'), (6, '300'), (7, '350'), (8, '400'), (9, '450'), (10, '500'), (11, '550'), (12, '600'), (13, '650'), (14, '700'), (15, '750'), (16, '800')], verbose_name='Km a Recorrer')),
                ('Mercaderia', models.CharField(max_length=30)),
                ('Toneladas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Tarifa', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Documentación', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('Facturado', models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default='No', verbose_name='Viaje Facturado')),
                ('Fecha_Factura', models.DateField()),
                ('Nro_Factura', models.CharField(max_length=30)),
                ('Camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Misviajes.vehiculos')),
                ('Cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Misviajes.entidades')),
                ('Origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Misviajes.localidades')),
            ],
        ),
        migrations.CreateModel(
            name='avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
