# Generated by Django 4.0.5 on 2022-06-29 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoentidad', models.PositiveSmallIntegerField(choices=[(1, 'Camioneros'), (2, 'Cliente')], verbose_name='Tipo_Entidad')),
                ('Documento', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehiculo', models.PositiveSmallIntegerField(choices=[(1, 'Camion'), (2, 'Acoplado')], verbose_name='Tipo_Entidad')),
                ('Patente', models.CharField(max_length=7)),
                ('DescripVeh', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mercaderia', models.CharField(max_length=30)),
                ('Toneladas', models.IntegerField()),
                ('Tarifa', models.IntegerField()),
                ('Origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Misviajes.localidades')),
            ],
        ),
    ]
