# Generated by Django 4.0.5 on 2022-06-29 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Misviajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='Camion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Misviajes.vehiculos'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='Vehiculo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Camion'), (2, 'Acoplado')], verbose_name='Tipo_Veh'),
        ),
    ]
