# Generated by Django 4.0.5 on 2022-07-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Misviajes', '0002_viajes_camion_alter_vehiculos_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='Facturación',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Toneladas'), (2, 'Monto Fijo')], default=1, verbose_name='TipO_Fact'),
            preserve_default=False,
        ),
    ]
