# Generated by Django 4.0.5 on 2022-08-09 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Misviajes', '0002_viajes_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='Comentario',
            field=models.CharField(default='-', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viajes',
            name='Destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudaddestino', to='app_Misviajes.localidades', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='Mercaderia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Soja'), (2, 'Maiz'), (3, 'Trigo'), (4, 'Sorgo'), (5, 'Girasol'), (6, 'Expeller de Soja'), (7, 'Afrechillo de Trigo'), (8, 'Harina de Soja'), (9, 'Otras Mercaderias')], verbose_name='Mercadria'),
        ),
    ]
