# Generated by Django 4.0.5 on 2022-08-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Misviajes', '0003_viajes_comentario_alter_viajes_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='Comentario',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
