# Generated by Django 4.0.5 on 2022-07-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Misviajes', '0003_viajes_facturación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='Facturación',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='Origen',
            field=models.CharField(default='Tabossi', max_length=30),
            preserve_default=False,
        ),
    ]
