# Generated by Django 4.0.5 on 2022-07-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Misviajes', '0004_alter_viajes_facturación_alter_viajes_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='Camion',
            field=models.CharField(default='AB314CO', max_length=30),
            preserve_default=False,
        ),
    ]
