# Generated by Django 4.0.5 on 2022-08-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Misviajes', '0004_alter_viajes_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='Facturado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No')], verbose_name='Viaje Facturado'),
        ),
    ]
