# Generated by Django 4.0.5 on 2022-08-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Misviajes', '0005_alter_viajes_facturado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='Facturado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2, verbose_name='Viaje Facturado'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='Fecha_Factura',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='Mercaderia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Soja'), (2, 'Maiz'), (3, 'Trigo'), (4, 'Sorgo'), (5, 'Girasol'), (6, 'Expeller de Soja'), (7, 'Afrechillo de Trigo'), (8, 'Harina de Soja'), (9, 'Otras Mercaderias')], verbose_name='Mercaderia'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='Nro_Factura',
            field=models.CharField(default='', max_length=30),
        ),
    ]
