# Generated by Django 4.0.5 on 2022-07-09 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Misviajes', '0006_camioneros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='Camion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Misviajes.vehiculos'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='Facturación',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Toneladas'), (2, 'Monto Fijo')], verbose_name='Tipo_Fact'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='Origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Misviajes.localidades'),
        ),
    ]
