# Generated by Django 4.0.5 on 2022-07-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Misviajes', '0007_alter_viajes_camion_alter_viajes_facturación_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='Origen',
            field=models.CharField(default='Tabossi', max_length=30),
            preserve_default=False,
        ),
    ]
