# Generated by Django 4.0.5 on 2022-07-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Misviajes', '0009_alter_viajes_camion_alter_viajes_facturación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='Facturación',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Toneladas'), (2, 'Monto Fijo')], verbose_name='Tipo_Fact'),
        ),
    ]
