# Generated by Django 4.0.5 on 2022-07-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Misviajes', '0010_alter_viajes_facturación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='Facturación',
            field=models.CharField(max_length=30),
        ),
    ]
